root: ../../megaman2/savestates

destination-prefix: "Mega Man 2 (U).fc"

savestate-configs:
  - name: Train-Sub34
    states:
      - file: 12-wily4/Mega Man 2 (U).fc9
        description: BBeam Boss
      - file: 08-bubble/Mega Man 2 (U).fc0
        description: Bubble Man start
      - file: 04-crash/Mega Man 2 (U).fc0
        description: Crash Man start
      - file: 12-wily4/Mega Man 2 (U).fc0
        description: Wily 4 Start
      - file: 12-wily4/Mega Man 2 (U).fc8
        description: Wily 4 Bottom floor
      - file: 12-wily4/drop-item2.fc0
        description: Wily 4 Drop Item 2
      - file: 07-metal/Mega Man 2 (U).fc0
        description: Metal Start
      - file: 07-metal/Mega Man 2 (U).fc7
        description: Metal Floor 2

  - name: Crash training (Normal)
    states:
      - file: 20240705-Crash/Mega Man 2 (U).fc0
        description: Crash Mets
      - file: 20240705-Crash//Mega Man 2 (U).fc8
        description: Crash Platforms
      - file: 20240705-Crash//Mega Man 2 (U).fc5
        description: Block tower; item 1 fest
      - file: 20240705-Crash//Mega Man 2 (U).fc3
        description: Twin ladders pre birds
      - file: 20240705-Crash//Mega Man 2 (U).fc4
        description: Mid-birds just starting Item 3
      - file: 20240705-Crash//Mega Man 2 (U).fc2
        description: Crash boss
      - file: 04-crash/Mega Man 2 (U).fc0
        description: Crash Man start

  - name: Wily 1 Training (Normal)
    states:
      - file: 09-wily1/Mega Man 2 (U).fc0
        description: Wiliy 1 start
      - file: 09-wily1/Mega Man 2 (U).fc9
        description: Trogdor platforming start
      - file: 20240705-wily/Mega Man 2 (U).fc4
        description: Wily 2 start
      - file: 20240705-wily/Mega Man 2 (U).fc5
        description: Wily 2 pre flash
      - file: 20240705-wily/Mega Man 2 (U).fc6
        description: Wily 3 start
      - file: 20240705-wily/Mega Man 2 (U).fc7
        description: Wily 3 Guts
      - file: 20240705-wily/Mega Man 2 (U).fc8
        description: Wily 3 Guts++
      - file: 20240705-wily/Mega Man 2 (U).fc9
        description: Wily 4 start
      - file: 20240705-wily/Mega Man 2 (U).fc0
        description: Wily 4 pre item 2
      - file: 20240705-wily/asdf.fc0
        description: Wily 5 start

  - name: Wood training (Normal)
    states:
      - file: 06-wood/Mega Man 2 (U).fc0
        description: Wood start
      - file: 20240705-wood/Mega Man 2 (U).fc3
        description: Wood after flash
      - file: 20240705-wood/Mega Man 2 (U).fc4
        description: Wood monkeys
      - file: 20240705-wood/Mega Man 2 (U).fc9
        description: Rabbit 1
      - file: 20240705-wood/Mega Man 2 (U).fc0
        description: Rabbit 3
      - file: 06-wood/Mega Man 2 (U).fc9
        description: Wood boss

  - name: Rando (Normal)
    states:
      - file: 20240706-Bosss/Mega Man 2 (U).fc3
        description: Flash boss
      - file: 20240706-Bosss/Mega Man 2 (U).fc5
        description: Quick boss
      - file: 20240706-Bosss/Mega Man 2 (U).fc6
        description: Air Hops
      - file: 20240706-Bosss/Mega Man 2 (U).fc7
        description: Air Level 2
      - file: 20240706-Bosss/Mega Man 2 (U).fc9
        description: Air Boss
      - file: 20240706-Bosss/Mega Man 2 (U).fc4
        description: Heat yoki
      - file: 20240706-Bosss/heatoneup.fcx
        description: Heat One up
      - file: 20240706-Bosss/Mega Man 2 (U).fc8
        description: Heat boss

  - name: Air Man Clouds
    states:
      - file: 20240717-AirManClouds/Mega Man 2 (U).fc4
        description: Air Man Pre cloud
      - file: 20240717-AirManClouds/Mega Man 2 (U).fc6
        description: Air Man Cloud 2
      - file: 20240717-AirManClouds/Mega Man 2 (U).fc5
        description: Air Man Cloud 3
      - file: 20240706-Bosss/Mega Man 2 (U).fc6
        description: Air Hops
      - file: 20240706-Bosss/Mega Man 2 (U).fc7
        description: Air Level 2
