root: ../../megaman2/savestates

destination-prefix: "Mega Man 2 (U).fc"

savestate-configs:
  - name: Train-Sub34
    states:
      - file: 01-flashman/Mega Man 2 (U).fc9
        description: Flash Man Boss
      - file: 12-wily4/Mega Man 2 (U).fc9
        description: BBeam Boss
      - file: 08-bubble/Mega Man 2 (U).fc0
        description: Bubble Man start
      - file: 04-crash/Mega Man 2 (U).fc0
        description: Crash Man start

